"""Add new models for Poll, PollOption, Question, and Feedback

Revision ID: 75ab51c2e678
Revises: 001
Create Date: 2026-02-06 22:56:48.313926
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '75ab51c2e678'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('option_text', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('responses', 'upvotes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_responses_slide_id', table_name='responses')
    op.alter_column('sessions', 'is_live',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_sessions_unique_code', table_name='sessions')
    op.alter_column('slides', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('ix_slides_session_order', table_name='slides')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_slides_session_order', 'slides', ['session_id', 'order'], unique=False)
    op.alter_column('slides', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index('ix_sessions_unique_code', 'sessions', ['unique_code'], unique=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'is_live',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index('ix_responses_slide_id', 'responses', ['slide_id'], unique=False)
    op.alter_column('responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('responses', 'upvotes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('poll_options')
    op.drop_table('questions')
    op.drop_table('polls')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
