"""Add response name and rating

Revision ID: e8d384600296
Revises: ab9a0181a62e
Create Date: 2026-02-12 22:55:12.938796
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'e8d384600296'
down_revision: Union[str, None] = 'ab9a0181a62e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('responses', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'rating')
    op.drop_column('responses', 'name')
    # ### end Alembic commands ###
