apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rforum.fullname" . }}-config
  labels:
    {{- include "rforum.labels" . | nindent 4 }}
data:
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.config.accessTokenExpireMinutes | quote }}
  ALGORITHM: "HS256"
  DATABASE_URL: "postgresql+asyncpg://rforum:$(POSTGRES_PASSWORD)@{{ include "rforum.fullname" . }}-postgres:5432/rforum"
  REDIS_URL: "redis://{{ include "rforum.fullname" . }}-redis:6379/0"
