apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rforum.fullname" . }}-pgdata
  labels:
    {{- include "rforum.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.storageClass }}
  storageClassName: {{ .Values.postgres.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
