apiVersion: v1
kind: Service
metadata:
  name: {{ include "rforum.fullname" . }}-postgres
  labels:
    {{- include "rforum.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "rforum.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - port: 5432
      targetPort: 5432
