apiVersion: v1
kind: Service
metadata:
  name: {{ include "rforum.fullname" . }}-redis
  labels:
    {{- include "rforum.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    {{- include "rforum.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: 6379
      targetPort: 6379
