apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rforum.fullname" . }}-secrets
  labels:
    {{- include "rforum.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key:        {{ .Values.secrets.secretKey       | b64enc | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
