/**
 * Shared branding constants for client-side PDF report generation (jsPDF).
 * Single source of truth so the event-level and session-level reports never
 * drift from each other again (the footer text previously read "Powered by
 * Tech4Good..." on one report and "Generated by Rforum..." on the other).
 */

export const FOOTER_TEXT = 'Generated by Rforum • rforum.t4gc.in';

export const MASCOT_URL = '/logo-mascot.webp';

/** RGB tuples for jsPDF's setFillColor/setTextColor/setDrawColor(...rgb) spread. */
export const BRAND = {
  purple: [124, 58, 237] as const,
  purpleSoft: [245, 243, 255] as const,
  text: [15, 23, 42] as const,
  muted: [71, 85, 105] as const,
  line: [226, 232, 240] as const,
  fill: [248, 250, 252] as const,
};

export const CHART_PALETTE: readonly (readonly [number, number, number])[] = [
  [124, 58, 237],
  [6, 182, 212],
  [16, 185, 129],
  [245, 158, 11],
  [236, 72, 153],
  [99, 102, 241],
  [20, 184, 166],
  [239, 68, 68],
];

/** Canvas-context font family used for text drawn inside chart canvases (pie/donut/word-cloud labels), chosen to visually match jsPDF's native "helvetica" text elsewhere in the report. */
export const CHART_FONT_FAMILY = 'Arial, Helvetica, sans-serif';
