apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rforum.frontend.fullname" . }}
  labels:
    {{- include "rforum.componentLabels" (dict "root" . "component" "frontend") | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "rforum.componentSelectorLabels" (dict "root" . "component" "frontend") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rforum.componentLabels" (dict "root" . "component" "frontend") | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rforum.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: frontend
          image: {{ include "rforum.frontend.image" . }}
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.path }}
              port: http
            initialDelaySeconds: {{ .Values.frontend.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.failureThreshold }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.path }}
              port: http
            initialDelaySeconds: {{ add .Values.frontend.probes.initialDelaySeconds 10 }}
            periodSeconds: {{ .Values.frontend.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.failureThreshold }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
